# Generated by Django 3.0.5 on 2020-05-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.IntegerField(null=True),
        ),
    ]
