# Generated by Django 3.0.5 on 2020-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200504_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score1byp1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score1byp2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score2byp1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score2byp2',
            field=models.IntegerField(null=True),
        ),
    ]
